[font]
size = 16


[colors.primary]
background =  '#000000'
foreground =  '#ffffff'

[colors.normal]
black   = '#101010'
red     = '#af5f00'
green   = '#cccc7c'
yellow  = '#ffff5f'
blue    = '#aeeeee'
magenta = '#505050'
cyan    = '#afffd7'
white   = '#fcfcce'

[colors.bright]
black   = '#101010'
red     = '#af5f00'
green   = '#cccc7c'
yellow  = '#ffff5f'
blue    = '#aeeeee'
magenta = '#505050'
cyan    = '#afffd7'
white   = '#fcfcce'