[terminal]
[terminal.shell]
program = '/opt/homebrew/bin/fish'
# program = '/bin/zsh'



[font]
size = 15.0

[font.normal]
family = "JetBrains Mono NL"
style = "Regular"

[font.bold]
family = "JetBrains Mono NL"
style = "Bold"

[font.italic]
family = "JetBrains Mono NL"
style = "Italic"

[font.bold_italic]
family = "JetBrains Mono NL"
style = "Bold Italic"


[colors.primary]
background = '#000000'
foreground = '#ffffff'

[colors.normal]
black   = '#1c1c1c'
red     = '#ff5f5f'
green   = '#87d75f'
yellow  = '#ffd75f'
blue    = '#5f87ff'
magenta = '#af5fff'
cyan    = '#5fd7d7'
white   = '#e4e4e4'

[colors.bright]
black   = '#3a3a3a'
red     = '#ff8787'
green   = '#afff87'
yellow  = '#ffff87'
blue    = '#87afff'
magenta = '#d7afff'
cyan    = '#87ffff'
white   = '#ffffff'
